In [1]:
from google.colab import files
uploaded=files.upload()

Saving batch 7 dataset-salary.csv to batch 7 dataset-salary.csv

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("batch 7 dataset-salary.csv")

df.head()

,Rating,Company Name,Job Title,Salary,Salaries Reported,Location,Employment Status,Job Roles
0,3.8,Sasken,Android Developer,400000,3,Bangalore,Full Time,Android
1,4.5,Advanced Millennium Technologies,Android Developer,400000,3,Bangalore,Full Time,Android
2,4.0,Unacademy,Android Developer,1000000,3,Bangalore,Full Time,Android
3,3.8,SnapBizz Cloudtech,Android Developer,300000,3,Bangalore,Full Time,Android
4,4.4,Appoids Tech Solutions,Android Developer,600000,3,Bangalore,Full Time,Android

Part A:

1. Load the dataset using Pandas and display the first 10 rows.

In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv("batch 7 dataset-salary.csv")

df.head()

,Rating,Company Name,Job Title,Salary,Salaries Reported,Location,Employment Status,Job Roles
0,3.8,Sasken,Android Developer,400000,3,Bangalore,Full Time,Android
1,4.5,Advanced Millennium Technologies,Android Developer,400000,3,Bangalore,Full Time,Android
2,4.0,Unacademy,Android Developer,1000000,3,Bangalore,Full Time,Android
3,3.8,SnapBizz Cloudtech,Android Developer,300000,3,Bangalore,Full Time,Android
4,4.4,Appoids Tech Solutions,Android Developer,600000,3,Bangalore,Full Time,Android

In [6]:
df.head(10)

,Rating,Company Name,Job Title,Salary,Salaries Reported,Location,Employment Status,Job Roles
0,3.8,Sasken,Android Developer,400000,3,Bangalore,Full Time,Android
1,4.5,Advanced Millennium Technologies,Android Developer,400000,3,Bangalore,Full Time,Android
2,4.0,Unacademy,Android Developer,1000000,3,Bangalore,Full Time,Android
3,3.8,SnapBizz Cloudtech,Android Developer,300000,3,Bangalore,Full Time,Android
4,4.4,Appoids Tech Solutions,Android Developer,600000,3,Bangalore,Full Time,Android
5,4.2,Freelancer,Android Developer,100000,3,Bangalore,Full Time,Android
6,3.7,SQUARE N CUBE,Android Developer,192000,3,Bangalore,Full Time,Android
7,3.1,Samsung R&D Institute India - Bangalore,Android Developer,400000,3,Bangalore,Full Time,Android
8,3.7,DXMinds Technologies,Android Developer,300000,3,Bangalore,Full Time,Android
9,3.6,Endeavour Software Technologies,Android Developer,600000,3,Bangalore,Full Time,Android

2.Find the total number of rows and columns.

In [7]:
rows, columns = df.shape
print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 22770
Number of columns: 8

3.List all column names

In [8]:
df.columns

Index(['Rating', 'Company Name', 'Job Title', 'Salary', 'Salaries Reported',
       'Location', 'Employment Status', 'Job Roles'],
      dtype='object')

4.Check data types of each column.

In [9]:
df.dtypes

Rating               float64
Company Name          object
Job Title             object
Salary                 int64
Salaries Reported      int64
Location              object
Employment Status     object
Job Roles             object
dtype: object

5. Identify missing or null values.

In [10]:
df.isnull().sum()

Rating               0
Company Name         1
Job Title            0
Salary               0
Salaries Reported    0
Location             0
Employment Status    0
Job Roles            0
dtype: int64

Part B: Data Cleaning & Preparation

6. Handle missing values appropriately and explain your method in comments.

In [12]:
# 1. Load dataset
df = pd.read_csv('/content/batch 7 dataset-salary.csv')

# 2. Check missing values
print("Before Cleaning:")
print(df.isnull().sum())

# 3. Handle missing values
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df['Location'] = df['Location'].fillna(df['Location'].mode()[0])
df['Job Title'] = df['Job Title'].fillna(df['Job Title'].mode()[0])
df['Company Name'] = df['Company Name'].fillna(df['Company Name'].mode()[0])

# 4. Verify
print("After Cleaning:")
print(df.isnull().sum())

Before Cleaning:
Rating               0
Company Name         1
Job Title            0
Salary               0
Salaries Reported    0
Location             0
Employment Status    0
Job Roles            0
dtype: int64
After Cleaning:
Rating               0
Company Name         0
Job Title            0
Salary               0
Salaries Reported    0
Location             0
Employment Status    0
Job Roles            0
dtype: int64

7.Check for duplicate records and remove them if present.

In [13]:
print("Before removing duplicates:")
print(df.duplicated().sum())

# Remove duplicate rows
df = df.drop_duplicates()

# Verify again
print("After removing duplicates:")
print(df.duplicated().sum())

Before removing duplicates:
0
After removing duplicates:
0

8.Convert relevant columns into correct data types (e.g., salary, experience).

In [14]:

print("Before Conversion:")
print(df.dtypes)

df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

df['Salaries Reported'] = pd.to_numeric(df['Salaries Reported'], errors='coerce')
df['Salaries Reported'] = df['Salaries Reported'].fillna(0)
df['Salaries Reported'] = df['Salaries Reported'].astype(int)

df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce')

print("\nAfter Conversion:")
print(df.dtypes)

Before Conversion:
Rating               float64
Company Name          object
Job Title             object
Salary                 int64
Salaries Reported      int64
Location              object
Employment Status     object
Job Roles             object
dtype: object

After Conversion:
Rating               float64
Company Name          object
Job Title             object
Salary                 int64
Salaries Reported      int64
Location              object
Employment Status     object
Job Roles             object
dtype: object

In [15]:
print(df.dtypes)

Rating               float64
Company Name          object
Job Title             object
Salary                 int64
Salaries Reported      int64
Location              object
Employment Status     object
Job Roles             object
dtype: object

9.Create a new column categorizing experience levels (Beginner, Intermediate, Expert).

In [16]:

def exp_level(x):
    if x <= 2:
        return "Beginner"
    elif x <= 5:
        return "Intermediate"
    else:
        return "Expert"

df['Experience Level'] = df['Salaries Reported'].apply(exp_level)

print(df[['Salaries Reported', 'Experience Level']].head())

   Salaries Reported Experience Level
0                  3     Intermediate
1                  3     Intermediate
2                  3     Intermediate
3                  3     Intermediate
4                  3     Intermediate

10.Standardize or clean text columns if required (e.g., job roles, locations).

In [17]:

# Convert text to lowercase
df['Job Title'] = df['Job Title'].str.lower()
df['Location'] = df['Location'].str.lower()
df['Company Name'] = df['Company Name'].str.lower()

# Remove extra spaces
df['Job Title'] = df['Job Title'].str.strip()
df['Location'] = df['Location'].str.strip()
df['Company Name'] = df['Company Name'].str.strip()

# Display result
print(df[['Job Title', 'Location', 'Company Name']].head())

           Job Title   Location                      Company Name
0  android developer  bangalore                            sasken
1  android developer  bangalore  advanced millennium technologies
2  android developer  bangalore                         unacademy
3  android developer  bangalore                snapbizz cloudtech
4  android developer  bangalore            appoids tech solutions

Part C: Data Analysis

11. Find the average salary based on experience level.

In [18]:
print(df.groupby('Experience Level')['Salary'].mean())

Experience Level
Beginner        695674.945407
Expert          639002.345550
Intermediate    721940.963545
Name: Salary, dtype: float64

12.Identify the highest and lowest paid job roles.

In [19]:
print(df.loc[df['Salary'].idxmax()][['Job Title', 'Salary']])
# Lowest paid job role
print(df.loc[df['Salary'].idxmin()][['Job Title', 'Salary']])

Job Title    software development engineer (sde)
Salary                                  90000000
Name: 18635, dtype: object
Job Title    web developer - intern
Salary                         2112
Name: 22563, dtype: object

13.Analyze salary distribution across different education levels.

In [20]:
print("Salary distribution based on Job Roles:")

print(df.groupby('Job Roles')['Salary'].describe())

Salary distribution based on Job Roles:
            count           mean           std       min       25%       50%  \
Job Roles
Android    2945.0  565911.003056  5.303402e+05   12000.0  252000.0  400000.0
Backend    1194.0  748518.164154  7.277008e+05   24000.0  255000.0  500000.0
Database    865.0  958584.046243  8.153262e+05  100000.0  500000.0  700000.0
Frontend   2163.0  610098.699954  6.136750e+05   12000.0  252000.0  420000.0
IOS        1631.0  695254.248927  5.282906e+05   12000.0  336000.0  588000.0
Java       1858.0  564709.907427  6.054523e+05    8448.0  252000.0  400000.0
Mobile      245.0  882282.971429  1.023473e+06   60000.0  300000.0  600000.0
Python      947.0  486022.791975  4.233985e+05   24000.0  228000.0  400000.0
SDE        8183.0  853794.522302  1.232829e+06   12000.0  384000.0  660000.0
Testing    1740.0  496298.188506  3.961338e+05   12672.0  288000.0  400000.0
Web         999.0  415451.947948  3.590405e+05    2112.0  200000.0  300000.0

                 75%         max
Job Roles
Android     700000.0   7100000.0
Backend    1000000.0   5200000.0
Database   1200000.0  10000000.0
Frontend    800000.0  10000000.0
IOS         900000.0   5200000.0
Java        700000.0  10000000.0
Mobile     1056000.0   9600000.0
Python      600000.0   6900000.0
SDE        1100000.0  90000000.0
Testing     600000.0   6600000.0
Web         500000.0   4400000.0

14.Find the average salary by location (if available).

In [21]:
print("Average Salary by Location:")
print(df.groupby('Location')['Salary'].mean())

Average Salary by Location:
Location
bangalore         735344.739593
chennai           584559.661513
hyderabad         679099.157376
jaipur            629135.802469
kerala            553577.481481
kolkata           710925.573034
madhya pradesh    677641.909677
mumbai            961180.368491
new delhi         658756.735632
pune              690476.311153
Name: Salary, dtype: float64

15.Identify top 5 highest salaries in the dataset.

In [22]:
print("Top 5 Highest Salaries:")
top5 = df.nlargest(5, 'Salary')
print(top5[['Job Title', 'Salary', 'Location']])

Top 5 Highest Salaries:
                                           Job Title    Salary   Location
18635            software development engineer (sde)  90000000  new delhi
4471                   oracle database administrator  10000000  bangalore
7121                      senior front end developer  10000000       pune
9260                           senior java developer  10000000    chennai
5819   lead ui designer, magento front-end developer   9900000  bangalore

16.Compare salaries between different job roles.

In [23]:
print("Salary comparison by Job Roles:")

print(df.groupby('Job Roles')['Salary'].mean().round(2))

Salary comparison by Job Roles:
Job Roles
Android     565911.00
Backend     748518.16
Database    958584.05
Frontend    610098.70
IOS         695254.25
Java        564709.91
Mobile      882282.97
Python      486022.79
SDE         853794.52
Testing     496298.19
Web         415451.95
Name: Salary, dtype: float64

Part D: Advanced Analysis

17. Analyze the relationship between experience and salary.

In [24]:

print("Experience column is not available in the dataset.")
print("Hence, relationship between experience and salary cannot be analyzed.")

Experience column is not available in the dataset.
Hence, relationship between experience and salary cannot be analyzed.

18.Identify any outliers in salary distribution

In [25]:

# Calculate Q1 and Q3
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Define lower and upper limits
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Find outliers
outliers = df[(df['Salary'] < lower_bound) | (df['Salary'] > upper_bound)]

print("Outliers in Salary:")
print(outliers[['Job Title', 'Salary']])

Outliers in Salary:
                        Job Title   Salary
96              android developer  2800000
106             android developer  2300000
145    android developer - intern  2200000
161             android developer  2100000
162             android developer  1900000
...                           ...      ...
22241               web developer  2400000
22271               web developer  4400000
22274               web developer  2900000
22366               web developer  2100000
22675               web developer  2016960

[1156 rows x 2 columns]

19.Find cases where high experience does not result in high salary.

In [26]:
print("Experience column not available in dataset.")
print("So cases where high experience does not result in high salary cannot be identified.")

Experience column not available in dataset.
So cases where high experience does not result in high salary cannot be identified.

20.Write five meaningful insights based on the dataset.

In [27]:
print("INSIGHTS FROM DATASET:\n")

# Insight 1
print("1. Average salary by Job Roles:")
print(df.groupby('Job Roles')['Salary'].mean(), "\n")

# Insight 2
print("2. Average salary by Location:")
print(df.groupby('Location')['Salary'].mean(), "\n")

# Insight 3
print("3. Top 5 highest salaries:")
print(df.nlargest(5, 'Salary')[['Job Title', 'Salary']], "\n")

# Insight 4
print("4. Salary distribution:")
print(df['Salary'].describe(), "\n")

# Insight 5
print("5. Number of salary records per Job Role:")
print(df['Job Roles'].value_counts())

INSIGHTS FROM DATASET:

1. Average salary by Job Roles:
Job Roles
Android     565911.003056
Backend     748518.164154
Database    958584.046243
Frontend    610098.699954
IOS         695254.248927
Java        564709.907427
Mobile      882282.971429
Python      486022.791975
SDE         853794.522302
Testing     496298.188506
Web         415451.947948
Name: Salary, dtype: float64

2. Average salary by Location:
Location
bangalore         735344.739593
chennai           584559.661513
hyderabad         679099.157376
jaipur            629135.802469
kerala            553577.481481
kolkata           710925.573034
madhya pradesh    677641.909677
mumbai            961180.368491
new delhi         658756.735632
pune              690476.311153
Name: Salary, dtype: float64

3. Top 5 highest salaries:
                                           Job Title    Salary
18635            software development engineer (sde)  90000000
4471                   oracle database administrator  10000000
7121                      senior front end developer  10000000
9260                           senior java developer  10000000
5819   lead ui designer, magento front-end developer   9900000

4. Salary distribution:
count    2.277000e+04
mean     6.953872e+05
std      8.843990e+05
min      2.112000e+03
25%      3.000000e+05
50%      5.000000e+05
75%      9.000000e+05
max      9.000000e+07
Name: Salary, dtype: float64

5. Number of salary records per Job Role:
Job Roles
SDE         8183
Android     2945
Frontend    2163
Java        1858
Testing     1740
IOS         1631
Backend     1194
Web          999
Python       947
Database     865
Mobile       245
Name: count, dtype: int64

Part E: NumPy Application

21. Convert salary or experience column into a NumPy array.

In [28]:
import numpy as np
salary_array = df['Salary'].to_numpy()
print("Salary as NumPy Array:")
print(salary_array)

Salary as NumPy Array:
[ 400000  400000 1000000 ...  192000  300000  300000]

22.Calculate mean, standard deviation, minimum, and maximum using NumPy.

In [ ]:
import numpy as np
# Convert to NumPy array
salary_array = df['Salary'].to_numpy()
# Calculations
print("Mean Salary:", np.mean(salary_array))
print("Standard Deviation:", np.std(salary_array))
print("Minimum Salary:", np.min(salary_array))
print("Maximum Salary:", np.max(salary_array))

Mean Salary: 695387.2112428634
Standard Deviation: 884379.5931947599
Minimum Salary: 2112
Maximum Salary: 90000000

23.Compare NumPy results with Pandas results.

In [29]:
import numpy as np

# NumPy calculations
salary_array = df['Salary'].to_numpy()

np_mean = np.mean(salary_array)
np_std = np.std(salary_array)
np_min = np.min(salary_array)
np_max = np.max(salary_array)

# Pandas calculations
pd_mean = df['Salary'].mean()
pd_std = df['Salary'].std()
pd_min = df['Salary'].min()
pd_max = df['Salary'].max()

# Print comparison
print("NumPy vs Pandas Comparison:\n")

print("Mean -> NumPy:", np_mean, "| Pandas:", pd_mean)
print("Std Dev -> NumPy:", np_std, "| Pandas:", pd_std)
print("Min -> NumPy:", np_min, "| Pandas:", pd_min)
print("Max -> NumPy:", np_max, "| Pandas:", pd_max)

NumPy vs Pandas Comparison:

Mean -> NumPy: 695387.2112428634 | Pandas: 695387.2112428634
Std Dev -> NumPy: 884379.5931947599 | Pandas: 884399.0136761819
Min -> NumPy: 2112 | Pandas: 2112
Max -> NumPy: 90000000 | Pandas: 90000000